### ISSUE TITLE
Support documentation.js?

### ISSUE THREAD

**Issue by xmo-odoo** [erikrose/sphinx-js#18]
[documentation](http://documentation.js.org) apparently tries to be a somewhat less crufty version of jsdoc (using a more standard parse &al), it uses the same tags (though may not quite have the same support) but tries to infer more, support flow by default and outputs json by default.

**Comment by erikrose** [comment]
Intriguing. It looks like a project with momentum. Did you find it compelling enough to use on your own code? Does it emit JSON in the same format JSDoc does? I'd be likely to entertain a patch that adds support for it; it's probably straightfoward enough. Though, if the output formats differ, we'll need to put an abstraction layer between the output and the things in renderers.py.

I'm curious how [MapBox](https://www.mapbox.com/mapbox-gl-js/api/) managed to put what appears to be introductory material before the reference-like API. A custom template? I don't see any other obvious affordance for content insertion in documentation.js's docs.

**Comment by xmo-odoo** [comment]
> It looks like a project with momentum. Did you find it compelling enough to use on your own code? 

I tried it because it had a linter and looked OK from afar, ended up not working better than JsDoc for my use case (I ultimately could use neither) though the linter was nice.

I also discovered after posting this issue that [the project may not be that healthful](https://macwright.org/2017/06/06/documentation-js.html) though it's definitely well sold/packaged, so YMMV… And the documentation is ironically not great.

> Does it emit JSON in the same format JSDoc does?

I have not checked (I don't know the JsDoc JSON format in the first place), I just saw that JSON output is pretty prominent.

> I'm curious how MapBox managed to put what appears to be introductory material before the reference-like API. A custom template? I don't see any other obvious affordance for content insertion in documentation.js's docs.

Lots of content in docstring, similar to JavaDocs? e.g. [ArrayList rendered documentation](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html), [ArrayList source](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/ArrayList.java).

Alternatively, they could be using e.g. includes/injections into markdown-written docstrings, something similar to the include directive in Sphinx.

**Comment by erikrose** [comment]
Yep, it doesn't look particularly lively anymore (mostly dependency updates at this point), and the author is having existential doubts. I think I'll hold off for now. Thanks for bringing it to my attention, though.

**Comment by erikrose** [comment]
esdoc supports some newer JS syntax but [has had maintenance issues](https://github.com/typhonjs-node-esdoc/esdoc).

**Comment by tmcw** [comment]
Hi there,

Tom from documentation.js here. To drill in a bit on that 'healthful' question... JSDoc is 'dead' by most counts, esdoc is mostly a single maintainer, and documentation.js is also _mostly_ a single maintainer (me). I'm taking a break from documentation.js this month (as detailed in that blog post) in hopes that other people join in.

All JavaScript documentation generators have fallen victim to the single-maintainer curse. All of them. That's really the reason why community, not my commit graph, is my focus right now.

Not to guilt for doing your own thing - after all, I didn't work on JSDoc because my design intent was significantly different. But, reports of project death spread quickly in this land, much like fire in a movie theater 🔥, so I want to be clear that, well, that's not what's happening.

Qs:

Re: how content insertions work: see the [configuring documentation](https://github.com/documentationjs/documentation/blob/master/docs/CONFIG.md), which allows you to insert arbitrary content between documentation sections. Mapbox uses both this _and_ a custom template to add that fancy content at the top. Admittedly, the documentation for documentation.js isn't that great (unfortunately I can't enjoy that irony), partially because I was crunched for time, and partially because it has changed a lot over the months.

Anyway, perhaps this is just a very longform version of "PRs desperately welcome." I'll be returning to the project next month, and its perceived health will certainly increase as a result :)

**Comment by erikrose** [comment]
Cheers. I'm glad documentation.js is alive and well! I'm surprised at the deadness of JSDoc; it has such a nice, canonical name, after all. ;-) I suppose if it breaks, I'll have to do something about it, but it's more likely that my next move (if it happens) will be to decouple sphinx-js from jsdoc a bit so people can plug in their own preferred extractors.

I just crave well-organized long-form documentation with an API reference in the back ([some](http://django-tidings.readthedocs.io/en/latest/) [examples](https://docs.djangoproject.com/en/1.11/)). I've spent so much time wandering around in confusion after being airdropped into somebody's API ref that I couldn't stomach perpetrating another instance of it in the Fathom docs. That's what I solved for myself with sphinx-js, and the more people I can drag along with me, the happier I'll be. :-)

**Comment by tmcw** [comment]
I don't want to make JSDoc seem totally dead either :) But it is moving somewhat slowly, especially, and unfortunately, at the spec level (the usejsdoc.org reference). It's pretty okay that it's slow-moving because it's pretty complete and, seriously, pretty darn good code.

Re: long-form documentation... it's definitely been, well, kind of a weird one for me. Most of the orgs I've seen already have systems for narrative / long-form docs, like Jekyll, CMS'es, wikis, other content generators, and it seems like possibly overstepping or reinventing to implement one in documentation.js - like, the task of 'generating a website' is so much more opinionated than 'extracting javascript documentation from javascript code', and it also stretches out in infinite ways that a dedicated website-building tool should focus on and a documentation generator probably shouldn't.

I guess Sphinx is the Python-side solution to that problem - the closest that JavaScript-land has is [Gatsby](https://github.com/gatsbyjs/gatsby), which is very present on my mind as I evolve documentation.js.

**Comment by erikrose** [comment]
"Let doc extractors be doc extractors, and let website builders be website builders." I couldn't agree more. I wouldn't mind at all if JSDoc just laid down JSON; its abilities as a website builder are pitiful enough that I spent a week writing my own shim to plug into a more capable website builder. I'd like to see more such tools specialize in the future. We could have some kind of common format or protocol for requesting things from extractors or their output, and then each markup language could have a way of spelling the requests (a la ReST's directives). Bam, m-to-n glory without everybody having to be all things to all people.
