### ISSUE TITLE
Help with use for CommonJS

### ISSUE THREAD

**Issue by bhofmei** [erikrose/sphinx-js#60]
I might just be an idiot but I can't figure out how to get this to work with CommonJS modules. I have files/modules using both `modules.exports = function()` and `exports.funcName = function()`. From what I've read, Sphnix-JS should be able to handle this but I keep getting "No JSDoc documentation was found".

Can you provide an example or something?

**Comment by erikrose** [comment]
Just to be clear, sphinx-js doesn't have any particular idea of modules; it knows about named files and symbols within them. So CommonJS per se shouldn't be a problem. (To be fair, I had to look up CommonJS and learn that it's what specifies the `exports` bits that I assumed were part of the node.js furniture.)

I think you will have trouble with modules that are directly assigning functions to `modules.exports`, since where will you put the JSDoc doclets? When there is no doclet, sphinx-js pretty much denies the existence of the undocumented thing. (I could see changing that now that we're better at extracting stuff from formal parameter lists.) However, something like this works, where a top-level eat-the-whole-module function is also given a local name:

```js
/**
 * Hi, mom.
 */
function foo() { return 5; }

modules.exports = foo
```

You should then be able to pull that into sphinx-js as "foo" or "whateverFileName.foo" (if you need to disambiguate). Does that help?

**Comment by bhofmei** [comment]
As an explanation that makes sense. Unfortunately I still can't get it to work.

**Comment by erikrose** [comment]
And actually, if you put the doclet just before the `exports` definition, it works fine:

```js
/**
 * Hi, mom.
 */
modules.exports = foo => 5
```

You'd have to call it "exports" in your sphinx-js directives.
